'use client'
//import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import { QuioscoProvider } from '@/context/QuioscoProvider'
// import 'react-responsive-modal/styles.css';
// import { Modal } from 'react-responsive-modal';
import useQuiosco from '@/hook/useQuiosco'
//import Modal from '@/components/Modal'
//import  Modal from 'react-modal'
//const inter = Inter({ subsets: ['latin'] })
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
import Admin from './Administrador/page'
import { usePathname } from 'next/navigation';

import 'react-toastify/dist/ReactToastify.css';


export default function RootLayout({ children }) {

  const pathname = usePathname();

  return (
    <html lang="en">
      <body 
      //className={inter.className}
      >
        {
          pathname.includes('/Administrador') 
          
          ? 
          
          <Admin/> 
          
          : 

          <QuioscoProvider>
        
          <div className="md:flex">
           <aside className="md:w-4/12 xl:w-1/4 2xl:w-1/5"> <Sidebar/></aside>
        
            
           
           
            <main className="md:w-8/12 xl:w-3/4 2xl:w-4/5  h-screen overflow-y-scroll" >
              <div className="p-10 mt-10"> 
             
              {children}
              </div>
          
            </main>
         
         </div>
    
             
          </QuioscoProvider>
       
          
          
          
        }
        
     
          {/* { modal && (
          <Modal isOpen={modal} onClose={onCloseModal}  
          //   style={{
          //     content: {
          //       top: '50%',
          //       left: '50%',
          //       right: 'auto',
          //       bottom: 'auto',
          //       marginRight: '-50%',
          //       transform: 'translate(-50%, -50%)',
          //     },
          //   }}
          >
             
          </Modal>
          )
          } */}
      
        
        </body>
    </html>
  )
}

